In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('laptopPrice.csv')

In [4]:
print(data.head())

    brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0    ASUS           Intel        Core i3            10th   4 GB     DDR4   
1  Lenovo           Intel        Core i3            10th   4 GB     DDR4   
2  Lenovo           Intel        Core i3            10th   4 GB     DDR4   
3    ASUS           Intel        Core i5            10th   8 GB     DDR4   
4    ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4   

      ssd      hdd       os  os_bit graphic_card_gb  weight     warranty  \
0    0 GB  1024 GB  Windows  64-bit            0 GB  Casual  No warranty   
1    0 GB  1024 GB  Windows  64-bit            0 GB  Casual  No warranty   
2    0 GB  1024 GB  Windows  64-bit            0 GB  Casual  No warranty   
3  512 GB     0 GB  Windows  32-bit            2 GB  Casual  No warranty   
4    0 GB   512 GB  Windows  64-bit            0 GB  Casual  No warranty   

  Touchscreen msoffice  Price   rating  Number of Ratings  Number of Reviews  
0      

In [15]:
data = pd.get_dummies(data, drop_first=True)

# Display the converted dataset
print("Converted Data:")
print(data.head())

Converted Data:
   Price  Number of Ratings  Number of Reviews  brand_ASUS  brand_Avita  \
0  34649                  3                  0           1            0   
1  38999                 65                  5           0            0   
2  39999                  8                  1           0            0   
3  69990                  0                  0           1            0   
4  26990                  0                  0           1            0   

   brand_DELL  brand_HP  brand_Lenovo  brand_MSI  brand_acer  ...  \
0           0         0             0          0           0  ...   
1           0         0             1          0           0  ...   
2           0         0             1          0           0  ...   
3           0         0             0          0           0  ...   
4           0         0             0          0           0  ...   

   Touchscreen_Yes  msoffice_Yes  rating_2 stars  rating_3 stars  \
0                0             0               1  

In [18]:
bins = [0, 50000, 100000, 150000, 200000, np.inf]  # Example price bins
labels = [1, 2, 3, 4, 5]  # Example labels for price ranges
data['Price_Range'] = pd.cut(data['Price'], bins=bins, labels=labels)

In [19]:
X = data.drop(columns=['Price', 'Price_Range'])
y = data['Price_Range']


In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt


In [22]:
model = RandomForestClassifier(n_estimators=100, random_state=42)


In [23]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

Accuracy: 1.00
Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        79
           3       1.00      1.00      1.00        28
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         4

    accuracy                           1.00       165
   macro avg       1.00      1.00      1.00       165
weighted avg       1.00      1.00      1.00       165

Confusion Matrix:
[[50  0  0  0  0]
 [ 0 79  0  0  0]
 [ 0  0 28  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0  4]]
